---
title: "Methods Section"
output:
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Model

  We used a hierarchical framework to estimate Bayesian means of total emissions and resource use across five stressors (greenhouse gas [kg CO~2~-eq], nitrogen [kg N-eq], phosphorus [kg P-eq], land [m^2^a] and water [m^3^]). We do this for all unique scientific names (e.g., Cyprinidae, *Cyprinus carpio*) found in our compiled LCA data as well as for aggregated groups of taxa (e.g., miscellaneous carps). Specifically, our model structure has study $i$, nested in scientific name $j$, nested in taxa group $k$. All Bayesian models were run using Markov Chain Monte Carlo (MCMC) algorithms in Stan (Stan Development Team, 2020) and called from R (R Core Team, 2020) using the R package, $rstan$ (Stan Development Team, 2019). All models converged (i.e., diagnostics for all parameters showed 0.99 < $\widehat{R}$ < 1.01, $n_{eff}/N$ > 0.1, and no divergent transitions) after 2500 iterations run on 4 chains. For each stressor, we calculate total emissions and resource use as the sum of their off-farm (feed-associated) and on-farm components as described below. 

# Off-farm (feed-associated) stressors

  For off-farm stressors, we modelled the dry weight feed conversion ratio of study $i$, $FCR_i$, as:

$$FCR_i \sim normal(\mu_{FCR_{j[i]}}, \sigma_{FCR_{j[i]}})$$
$$\mu_{FCR_{j[i]}} \sim normal(\mu_{FCR_{k[j]}}, \sigma_{FCR_{k[j]}})$$
$$\sigma_{FCR_{j[i]}}, \sigma_{FCR_{k[j]}}\sim halfCauchy(0,1)$$

such that $\mu_{FCR_{j[i]}}$ and $\mu_{FCR_{k[j]}}$ are the mean FCR for scientific name $j$ and and taxa group $k$, respectively, and $\sigma_{FCR_{j[i]}}$ and $\sigma_{FCR_{k[j]}}$ are their respective standard deviations. To help with convergence we apply weakly-informative half-Cauchy priors on the scientific name and taxa group level $\sigma$’s. 

  For off-farm stressors, we also modelled the proportions of feed originating from soy, crops, livestock, and fisheries. For each study i, Xi is a vector of feed proportions that sums to 1. We modelled this vector as:

$$X_i = (X_{soy}, X_{crops}, X_{livestock}, X_{fisheries}) \sim Dirichlet(\alpha_{j[i]})$$
such that $\alpha_{j[i]}$ is a shape parameter describing the distribution (uniform or degenerate) of the feed proportions for scientific name $j$. We then reparameterized  $\alpha_{j[i]}$ as:

$$\alpha_{j[i]} = K_{j[i]} * \theta_{j[i]}$$
such that $\theta_{j[i]}$ is the vector of estimated feed proportions of scientific name $j$ and  $K_{j[i]}$ is the sample size (number of studies) for scientific name $j$ (Stan Development Team, 2020). To obtain our taxa group estimates, we modelled the estimated scientific name feed proportions $\theta_{j[i]}$ as Dirichlet distributed, and reparameterized this as above to obtain a vector of estimated feed proportions for taxa group $k$:

$$ \theta_{j[i]} \sim Dirichlet(\alpha_{k[j]})$$
$$\alpha_{k[j]} = K_{k[j]} * \theta_{k[j]}$$
  Finally, we calculated the species and taxa group level off-farm (i.e., feed-associated) stress ($S_{feed[stressor]}$) for each stressor (GHG, N, P, land, and water) by multiplying the feed requirements by the associated stressors of the feed, weighted by the feed composition:
$$S_{feed[stressor]}=FCR\sum_{f=1}^{4}S_fp_f$$
Here, $f$ indexes the four feed ingredients (soy, other crops, fishmeal and fish oil, and livestock byproducts). $S_f$ is a constant that quantifies the stressors of each feed ingredient $f$, while $FCR$ and $p_f$ are the posterior distributions of the estimated dry weight feed conversion ratio and the proportion of each feed component $f$.

## On-farm stressors

  On-farm nitrogen and phosphorus stressors are calculated from the same species and taxa-level means of $FCR$ and feed proportions, $p_f$, described above for off-farm stressors. Here, on-farm N and P stress are estimated as the difference between the N and P content of each feed component and the species-specific N and P contents of each seafood product such that:
$$S_{nonfeed[nitrogen]}=FCR\sum_{f=1}^{4}N_fp_f−N_{fish}$$
$$S_{nonfeed[nitrogen]}=FCR\sum_{f=1}^{4}P_fp_f−N_{fish}$$
where $N_f$ and $P_f$ represent the nitrogen and phosphorus content of feed component $f$ and $N_{fish}$ and $P_{fish}$ represent the species-specific nitrogen and phosphorus content of a unit of fish or shellfish. 
  While on-farm stress, $S_{nonfeed}$, for N and P are both derived from the Bayesian means of FCR and the feed proportions, the other stressors, land, GHG, and water, are derived from nested means of the calculated stressor as described below. The non-feed associated land use refers to the land area allocated to the growth of a unit of output which applies to aquaculture systems that are ponds, recirculating systems and tanks. We calculated land stress ($S_{nonfeed[land]}$; m^2^a / tonne) as the reciprocal of annual yield  (Y; tonnes / m^2^):
$$S_{nonfeed[land]}=\frac{1}{Y}$$
  The on-farm greenhouse gas emissions ($S_{nonfeed[GHG]}$) are calculated as the electricity use times the country-specific GHG emissions, plus the diesel, petrol, and natural gas use times each of their GHG stressor factors:
$$S_{nonfeed[GHG]}=\sum_{q=1}^{4}G_qE_q$$
Here, $q$ indexes the four energy sources (electricity, diesel, petrol, and natural gas), $G_q$ represents the GHG emissions of energy source $q$, and $E_q$ represents the energy use of source $q$. While energy use does contribute to the other stressors, we only include it in the GHG stressor since the contribution to the other stressors is small. 
  To calculate the on-farm water use, we estimated the evaporative losses over the surface area allocated to the unit of production as:
$$S_{nonfeed[water]}=VTS_{nonfeed[land]}$$
where $V$ represents the country-specific average surface evaporation rate and $T$ represents the grow-out period. 
  We then model the Bayesian means for on-farm land, GHG, and water stressors with study $i$ nested in scientific name $j$, nested in taxa group $k$ as shown below:
$$S_{nonfeed[stressor]}\sim normal(\mu_{Stressor_{j[i]}}, \sigma_{Stressor_{j[i]}})$$
$$\mu_{Stressor_{j[i]}}\sim normal(\mu_{Stressor_{k[j]}}, \sigma_{Stressor_{k[j]}})$$
  To help with convergence, we apply the following hyperpriors on all ’s at the scientific name and taxa group level. Specifically, 
$$\sigma_{GHG_{j[i]}}, \sigma_{GHG_{k[j]}} \sim halfCauchy(0, 1000)$$
$$\sigma_{Land_{k[j]}}, \sigma_{Land_{k[j]}} \sim halfCauchy(0, 10000)$$
$$\sigma_{Water_{k[j]}}, \sigma_{Water_{k[j]}} \sim halfCauchy(0, 100)$$
  Finally, we apply priors on mean FCR at the taxa-level for all taxa groups except “miscellaneous diadromous fishes”:
$$\mu_{FCR_{k[j]}} \sim normal(prior, 1)$$
We focus on FCR because it is a parameter found in all of our stressor models for which there is considerable information. Priors were derived from… Re-running the models with vs without these priors caused slight shifts in the posterior, but the major results (i.e., ordering of taxa results from highest to lowest stress) did not change.

# Missing Data Imputation

  Missing data for FCR, feed proportions, yield, and all energy inputs (electricity, petrol, diesel, and natural gas) were imputed using taxa group as a categorical predictor and intensity and system type as ordinal predictors. In other words, the predicted value for missing data is pulled to the mean of other LCA studies of the same taxa group, intensity, and system type. For the feed proportions we used a Bayesian Dirichlet regression and for all other variables we used a Bayesian gamma regression with log link to estimate the effects of all predictors on each variable. For each missing data point, we used the median of their predicted posterior distribution as the imputed value for all subsequent analyses. All predictor variables are centered and scaled by two standard deviations. All models were fitted using Stan and implemented with brms in R. All models converged (i.e., diagnostics for all parameters showed 0.99 <  $\widehat{R}$ < 1.01, $n_{eff}/N$ > 0.1, and no divergent transitions) after 5000 iterations run on 4 chains. For the gamma regressions, the following hyperpriors were implemented on the coefficients ($m_i$), intercept ($b$), and shape ($\alpha$) parameter for the gamma:

$$m_i \sim normal(0, 2.5)$$

$$b \sim normal(0, 5)$$

 $$\alpha \sim exponential(1)$$
